# Generated by Django 5.0.1 on 2024-02-19 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_book_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_cover',
            field=models.ImageField(default='upload_book/book-cover.png', upload_to='upload_book/'),
        ),
    ]
