# Generated by Django 5.0.1 on 2024-02-22 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_book_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('Fiction', 'Fiction'), ('Non-Fiction', 'Non-Fiction'), ('Academic', 'Academic'), ('Children', 'Children'), ('Art & Photography', 'Art & Photography'), ('Cookbooks', 'Cookbooks'), ('Travel', 'Travel'), ('Health & Wellness', 'Health & Wellness'), ('Religion & Spirituality', 'Religion & Spirituality'), ('Hobbies & Crafts', 'Hobbies & Crafts'), ('Sports & Recreation', 'Sports & Recreation'), ('Science Fiction & Fantasy', 'Science Fiction & Fantasy'), ('Horror', 'Horror'), ('Poetry', 'Poetry'), ('Drama', 'Drama'), ('Others', 'Others')], default='Others', max_length=50),
        ),
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.CharField(default='English', max_length=50),
        ),
        migrations.AddField(
            model_name='book',
            name='pages',
            field=models.PositiveIntegerField(default=2),
            preserve_default=False,
        ),
    ]
