# Generated by Django 5.0.1 on 2024-03-18 15:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0005_alter_book_book_cover_alter_book_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="is_sold",
            field=models.BooleanField(default=False),
        ),
    ]
