# Generated by Django 5.0.1 on 2024-03-16 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_remove_rental_country_remove_rental_state_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rental',
            old_name='address_line1',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='address_line2',
        ),
    ]
