# Generated by Django 5.0.1 on 2024-03-18 15:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rentals", "0003_rename_address_line1_rental_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rental",
            name="is_sold",
            field=models.BooleanField(default=False),
        ),
    ]
