# Generated by Django 5.0.1 on 2024-03-19 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0004_rental_is_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='agreement',
            field=models.PositiveIntegerField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='rental',
            name='appliances',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=5),
        ),
        migrations.AddField(
            model_name='rental',
            name='bathrooms',
            field=models.PositiveIntegerField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='rental',
            name='bedrooms',
            field=models.PositiveIntegerField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='rental',
            name='furnished',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=5),
        ),
        migrations.AddField(
            model_name='rental',
            name='parking',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=5),
        ),
        migrations.AlterField(
            model_name='rental',
            name='property_image',
            field=models.ImageField(upload_to='upload_property/'),
        ),
    ]
