# Generated by Django 5.0.1 on 2024-03-20 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_profile_bio_profile_course_profile_user_class_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='message',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='number',
            field=models.CharField(help_text='Enter your number  ', max_length=15, verbose_name='Phone Number'),
        ),
    ]
