# Generated by Django 5.0.1 on 2024-02-27 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freestuff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='freestuffitem',
            name='category',
            field=models.CharField(blank=True, choices=[('Electronics', 'Electronics'), ('Clothing', 'Clothing'), ('Shoes', 'Shoes'), ('Furniture', 'Furniture'), ('Book', 'Book'), ('Others', 'Others')], default='Others', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='freestuffitem',
            name='condition',
            field=models.CharField(choices=[('New', 'New'), ('Used', 'Used')], default='New', max_length=255),
        ),
    ]
