# Generated by Django 5.0.1 on 2024-03-18 15:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("freestuff", "0002_freestuffitem_category_freestuffitem_condition"),
    ]

    operations = [
        migrations.AddField(
            model_name="freestuffitem",
            name="is_sold",
            field=models.BooleanField(default=False),
        ),
    ]
