# Generated by Django 4.2.10 on 2024-02-18 06:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("Electronics", "Electronics"),
                    ("Clothing", "Clothing"),
                    ("Shoes", "Shoes"),
                    ("Books", "Books"),
                    ("Furniture", "Furniture"),
                    ("Others", "Others"),
                ],
                default=1,
                max_length=255,
            ),
            preserve_default=False,
        ),
    ]
