# Generated by Django 4.2.10 on 2024-02-18 12:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_product_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="interested_count",
            field=models.IntegerField(default=0),
        ),
    ]
