# Generated by Django 5.0.1 on 2024-02-23 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_interested_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Electronics', 'Electronics'), ('Clothing', 'Clothing'), ('Shoes', 'Shoes'), ('Furniture', 'Furniture'), ('Others', 'Others')], max_length=255),
        ),
    ]
