# Generated by Django 5.0.1 on 2024-03-18 15:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0006_alter_product_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_sold",
            field=models.BooleanField(default=False),
        ),
    ]
